name = "boymodercraft forge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf3ada0ee93f2ef89abdcfa4e65cdc1ff67544f56dda4538d5f1743b51ee7787"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
