name = "boymodercraft forge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bffbc8b9d70eb5acb125baf3c452634060b3401101c9ace8ca444f85722ce59"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
