name = "boymodercraft forge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25b085862188bd1c313a79cac54999aa0d52dca39415181dac89803add2690bd"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
