name = "boymodercraft forge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dab92ecfe7f0848bf39ae71b3dafb0e1bfd94e5a493280f0db04ceca58debfd"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
